#!/bin/bash
# Wrap a ROOT macro as a script.
#
#  Check the output of GUNDAM 200NormalizationFit.sh against the
#  expected values.
#
root -b -n <<EOF
#include <iostream>
#include <string>
#include <memory>
#include <cmath>

#include <TFile.h>
#include <TH1F.h>
#include <TTree.h>

std::string args{"$*"};
int status{0};

/// Fail with message if "v1" evaluates to false.  THIS IS COPIED
/// HERE TO AVOID DEPENDENCIES
#define EXPECT(msg,v1)                                      \
    do {                                                    \
        if (not (v1)) {                                     \
            std::cout << "FAIL:";                           \
            ++ status;                                      \
        } else {                                            \
            std::cout << "SUCCESS:";                        \
        }                                                   \
        std::cout << " " << msg                             \
                  << " [ (" << #v1 << ") --> " << v1 << "]" \
                  << std::endl;                             \
    } while (false)

/// Fail if fractional difference between "v1" and "v2" is larger than "tol"
/// THIS IS COPIED HERE TO AVOID DEPENDENCIES
#define TOLERANCE(msg,v1,v2,tol)                            \
    do {                                                    \
        double v = (v1)>0 ? (v1): -(v1);                    \
        double vv = (v2)>0 ? (v2): -(v2);                   \
        double d = std::abs((v1)-(v2));                     \
        double r = d/std::max(0.5*(v+vv),(tol));            \
        if (r > (tol)) {                                    \
            std::cout << "FAIL:";                           \
            ++ status;                                      \
        } else {                                            \
            std::cout << "SUCCESS:";                        \
        }                                                   \
        std::cout << " " << msg                             \
                  << std::setprecision(8)                   \
                  << std::scientific                        \
                  << " (" << r << "<" << (tol) << ")"       \
                  << " [" << #v1 << "=" << (v1)             \
                  << " " << #v2 << "=" << (v2)              \
                  << " " << d << "]"                        \
                  << std::endl;                             \
    } while(false);

int main() {
    std::shared_ptr<TFile> fit(new TFile("200NormalizationFit.root","old"));

    EXPECT("File pointer is not null",fit);
    if (!fit) return status;

    EXPECT("File must be open", fit->IsOpen());
    if (not fit->IsOpen()) return status;

    TH1* postFitErrorsHesse
        = dynamic_cast<TH1*>(fit->Get(
                                 "FitterEngine"
                                 "/postFit"
                                 "/Hesse"
                                 "/errors"
                                 "/Normalizations"
                                 "/values"
                                 "/postFitErrors_TH1D"));
    EXPECT("postFitErrors must exist",  postFitErrorsHesse);

    // Don't try to continue if the data is missing from the file.
    if (not postFitErrorsHesse) return status;

    std::shared_ptr<TFile> mcmc(new TFile("200NormalizationMCMC.root","old"));

    TTree* tree
        = dynamic_cast<TTree*>(mcmc->Get(
                                 "FitterEngine"
                                 "/fit"
                                 "/MCMC"));

    std::vector<double> points;
    std::vector<double>* addrPoints = &points;

    TH1F positiveC("positiveC", "The first parameter",100, 0.7, 0.9);
    TH1F negativeC("negativeC", "The second parameter",100, 0.5, 0.7);
    tree->SetBranchAddress("Points",&addrPoints);
    for (int i=0; i < tree->GetEntries(); ++i) {
        tree->GetEntry(i);
        positiveC.Fill(points[0]);
        negativeC.Fill(points[1]);
    }

    positiveC.Draw();
    gPad->Print("900NormalizationMCMCCheck.pdf(");
    negativeC.Draw();
    gPad->Print("900NormalizationMCMCCheck.pdf)");

    // Expected accuracy.  This is based on assuming an assumed effective
    // sample size factor of 10 (i.e. it takes that many steps to become
    // uncorrelated, that's probably optimisitic).
    double entries = positiveC.GetEntries();
    double assumedEffectiveSampleFactor = 10;
    double relativeSigma = 1.0/std::sqrt(entries/assumedEffectiveSampleFactor);

    // The expected values are for the data generated by
    // 100NormalizationTree.C.  They need to be changed if that tree is
    // changed.
    double allowedSigma = 5.0;
    TOLERANCE("Check MCMC matches HESSE value for #0_Positive_C",
              positiveC.GetMean(),
              postFitErrorsHesse->GetBinContent(1), allowedSigma*relativeSigma);
    TOLERANCE("Check MCMC matches HESSE value for #0_Positive_C",
              positiveC.GetRMS(),
              postFitErrorsHesse->GetBinError(1), allowedSigma*relativeSigma);
    TOLERANCE("Check MCMC RMS matches HESSE value for #1_Negative_C",
              negativeC.GetMean(),
              postFitErrorsHesse->GetBinContent(2), allowedSigma*relativeSigma);
    TOLERANCE("Check MCMC RMS matches HESSE value for #1_Negative_C",
              negativeC.GetRMS(),
              postFitErrorsHesse->GetBinError(2), allowedSigma*relativeSigma);

    fit->Close();
    mcmc->Close();

    return status;
}
exit(main());
EOF
# Local Variables:
# mode:c++
# c-basic-offset:4
# End:
