#!/bin/bash
# Wrap a ROOT macro as a script.
#
#  Check the output of GUNDAM 200NormalizationAsimov.sh against the
#  expected values.
#
root -b -n <<EOF
#include <iostream>
#include <string>
#include <memory>
#include <cmath>

#include <TFile.h>
#include <TH1.h>

std::string args{"$*"};
int status{0};

#define EXPECT(msg,v1)                                                  \
    do {                                                                \
        if (not (v1)) {                                                 \
            std::cout << "FAIL:";                                       \
            ++ status;                                                  \
        } else {                                                        \
            std::cout << "SUCCESS:";                                    \
        }                                                               \
        std::cout << " " << msg                                         \
                  << " [ (" << #v1 << ") --> " << v1 << "]"             \
                  << std::endl;                                         \
    } while (false)


#define TOLERANCE(msg,v1,v2,tol)                                        \
    do {                                                                \
        if (std::abs(v1-v2) > tol) {                                    \
            std::cout << "FAIL:";                                       \
            ++ status;                                                  \
        } else {                                                        \
            std::cout << "SUCCESS:";                                    \
        }                                                               \
        std::cout << " " << msg                                         \
                  << std::setprecision(15)                              \
                  << " [" << #v1 << "=" << (v1)                         \
                  << " " << #v2 << "=" << (v2)                          \
                  << " " << std::abs(v1-v2) << ">" << (tol) << "]"      \
                  << std::endl;                                         \
    } while(false);

int main() {
    std::shared_ptr<TFile> file(new TFile("200NormalizationAsimov.root","old"));

    EXPECT("File pointer is not null",file);
    if (!file) return status;

    EXPECT("File must be open", file->IsOpen());
    if (not file->IsOpen()) return status;

    TH1* postFitErrors
        = dynamic_cast<TH1*>(file->Get(
                                 "FitterEngine"
                                 "/postFit"
                                 "/Migrad"
                                 "/errors"
                                 "/Normalizations"
                                 "/values"
                                 "/postFitErrors_TH1D"));
    EXPECT("postFitErrors must exist",  postFitErrors);

    TMatrixD* covariance
        = dynamic_cast<TMatrixD*>(file->Get(
                                      "FitterEngine"
                                      "/postFit"
                                      "/Migrad"
                                      "/errors"
                                      "/Normalizations"
                                      "/matrices"
                                      "/Covariance_TMatrixD"));
    EXPECT("covariance must exist",  covariance);

    // Don't try to continue if the data is missing from the file.
    if (not postFitErrors) return status;
    if (not covariance) return status;

    postFitErrors->Draw();
    gPad->Print("900NormalizationAsimovCheck.pdf");
    covariance->Print();

    // Change this to set the expected absolute tolerance.
    double tolerance = 1E-8;

    // The expected values are for the data generated by
    // 100NormalizationTree.C.  They need to be changed if that tree is
    // changed.
    TOLERANCE("Check nominal value for #0_Positive_C",
              postFitErrors->GetBinContent(1), 1.0, tolerance);
    TOLERANCE("Check variance for #0_Positive_C",
              (*covariance)(0,0), 0.000290364, tolerance);

    TOLERANCE("Check nominal value for #1_Negative_C",
              postFitErrors->GetBinContent(2), 1.0, tolerance);
    TOLERANCE("Check variance for #1_Negative_C",
              (*covariance)(1,1), 0.000289376, tolerance);

    TOLERANCE("Check covariance",
              (*covariance)(0,1), 0.0, tolerance);

    file->Close();

    return status;
}
exit(main());
EOF
# Local Variables:
# mode:c++
# c-basic-offset:4
# End:
