//
// File generated by rootcint at Tue Apr 26 19:18:29 2016

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME XsecFitterDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "XsecFitterDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void XsecFitter_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_XsecFitter(void *p = 0);
   static void *newArray_XsecFitter(Long_t size, void *p);
   static void delete_XsecFitter(void *p);
   static void deleteArray_XsecFitter(void *p);
   static void destruct_XsecFitter(void *p);
   static void streamer_XsecFitter(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::XsecFitter*)
   {
      ::XsecFitter *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::XsecFitter >(0);
      static ::ROOT::TGenericClassInfo 
         instance("XsecFitter", ::XsecFitter::Class_Version(), "./XsecFitter.hh", 15,
                  typeid(::XsecFitter), DefineBehavior(ptr, ptr),
                  &::XsecFitter::Dictionary, isa_proxy, 0,
                  sizeof(::XsecFitter) );
      instance.SetNew(&new_XsecFitter);
      instance.SetNewArray(&newArray_XsecFitter);
      instance.SetDelete(&delete_XsecFitter);
      instance.SetDeleteArray(&deleteArray_XsecFitter);
      instance.SetDestructor(&destruct_XsecFitter);
      instance.SetStreamerFunc(&streamer_XsecFitter);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::XsecFitter*)
   {
      return GenerateInitInstanceLocal((::XsecFitter*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::XsecFitter*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *XsecFitter::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *XsecFitter::Class_Name()
{
   return "XsecFitter";
}

//______________________________________________________________________________
const char *XsecFitter::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::XsecFitter*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int XsecFitter::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::XsecFitter*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void XsecFitter::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::XsecFitter*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *XsecFitter::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::XsecFitter*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void XsecFitter::Streamer(TBuffer &R__b)
{
   // Stream an object of class XsecFitter.

   TObject::Streamer(R__b);
}

//______________________________________________________________________________
void XsecFitter::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class XsecFitter.
      TClass *R__cl = ::XsecFitter::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*mcHisto", &mcHisto);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*rand", &rand);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*m_dir", &m_dir);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_fitpara", (void*)&m_fitpara);
      R__insp.InspectMember("vector<AnaFitParameters*>", (void*)&m_fitpara, "m_fitpara.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_nparclass", (void*)&m_nparclass);
      R__insp.InspectMember("vector<int>", (void*)&m_nparclass, "m_nparclass.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_samples", (void*)&m_samples);
      R__insp.InspectMember("vector<AnaSample*>", (void*)&m_samples, "m_samples.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_npar", &m_npar);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_calls", &m_calls);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "m_freq", &m_freq);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "reg_p1", &reg_p1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "par_names", (void*)&par_names);
      R__insp.InspectMember("vector<std::string>", (void*)&par_names, "par_names.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "par_prefit", (void*)&par_prefit);
      R__insp.InspectMember("vector<double>", (void*)&par_prefit, "par_prefit.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "par_postfit", (void*)&par_postfit);
      R__insp.InspectMember("vector<double>", (void*)&par_postfit, "par_postfit.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "par_errfit", (void*)&par_errfit);
      R__insp.InspectMember("vector<double>", (void*)&par_errfit, "par_errfit.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "par_toydata", (void*)&par_toydata);
      R__insp.InspectMember("vector<double>", (void*)&par_toydata, "par_toydata.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vec_chi2_stat", (void*)&vec_chi2_stat);
      R__insp.InspectMember("vector<double>", (void*)&vec_chi2_stat, "vec_chi2_stat.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "vec_chi2_sys", (void*)&vec_chi2_sys);
      R__insp.InspectMember("vector<double>", (void*)&vec_chi2_sys, "vec_chi2_sys.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_XsecFitter(void *p) {
      return  p ? new(p) ::XsecFitter : new ::XsecFitter;
   }
   static void *newArray_XsecFitter(Long_t nElements, void *p) {
      return p ? new(p) ::XsecFitter[nElements] : new ::XsecFitter[nElements];
   }
   // Wrapper around operator delete
   static void delete_XsecFitter(void *p) {
      delete ((::XsecFitter*)p);
   }
   static void deleteArray_XsecFitter(void *p) {
      delete [] ((::XsecFitter*)p);
   }
   static void destruct_XsecFitter(void *p) {
      typedef ::XsecFitter current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_XsecFitter(TBuffer &buf, void *obj) {
      ((::XsecFitter*)obj)->::XsecFitter::Streamer(buf);
   }
} // end of namespace ROOT for class ::XsecFitter

/********************************************************
* XsecFitterDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableXsecFitterDict();

extern "C" void G__set_cpp_environmentXsecFitterDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("XsecFitter.hh");
  G__cpp_reset_tagtableXsecFitterDict();
}
#include <new>
extern "C" int G__cpp_dllrevXsecFitterDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* XsecFitter */
static int G__XsecFitterDict_630_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   XsecFitter* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new XsecFitter((int) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) XsecFitter((int) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new XsecFitter[n];
       } else {
         p = new((void*) gvp) XsecFitter[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new XsecFitter;
       } else {
         p = new((void*) gvp) XsecFitter;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__XsecFitterDictLN_XsecFitter));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__XsecFitterDict_630_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((XsecFitter*) G__getstructoffset())->SetSeed((int) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__XsecFitterDict_630_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((XsecFitter*) G__getstructoffset())->fcn(*(Int_t*) G__Intref(&libp->para[0]), (Double_t*) G__int(libp->para[1])
, *(Double_t*) G__Doubleref(&libp->para[2]), (Double_t*) G__int(libp->para[3])
, (Int_t) G__int(libp->para[4]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__XsecFitterDict_630_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((XsecFitter*) G__getstructoffset())->InitFitter(*(vector<AnaFitParameters*>*) libp->para[0].ref, (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__XsecFitterDict_630_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((XsecFitter*) G__getstructoffset())->FixParameter(*((string*) G__int(libp->para[0])), (double) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__XsecFitterDict_630_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((XsecFitter*) G__getstructoffset())->Fit(*(vector<AnaSample*>*) libp->para[0].ref, (int) G__int(libp->para[1])
, (int) G__int(libp->para[2]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__XsecFitterDict_630_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((XsecFitter*) G__getstructoffset())->SetSaveMode((TDirectory*) G__int(libp->para[0]), (int) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__XsecFitterDict_630_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) XsecFitter::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__XsecFitterDict_630_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) XsecFitter::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__XsecFitterDict_630_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) XsecFitter::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__XsecFitterDict_630_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      XsecFitter::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__XsecFitterDict_630_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((XsecFitter*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__XsecFitterDict_630_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) XsecFitter::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__XsecFitterDict_630_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) XsecFitter::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__XsecFitterDict_630_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) XsecFitter::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__XsecFitterDict_630_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) XsecFitter::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__XsecFitterDict_630_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   XsecFitter* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new XsecFitter(*(XsecFitter*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__XsecFitterDictLN_XsecFitter));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef XsecFitter G__TXsecFitter;
static int G__XsecFitterDict_630_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (XsecFitter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((XsecFitter*) (soff+(sizeof(XsecFitter)*i)))->~G__TXsecFitter();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (XsecFitter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((XsecFitter*) (soff))->~G__TXsecFitter();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__XsecFitterDict_630_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   XsecFitter* dest = (XsecFitter*) G__getstructoffset();
   *dest = *(XsecFitter*) libp->para[0].ref;
   const XsecFitter& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* XsecFitter */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncXsecFitterDict {
 public:
  G__Sizep2memfuncXsecFitterDict(): p(&G__Sizep2memfuncXsecFitterDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncXsecFitterDict::*p)();
};

size_t G__get_sizep2memfuncXsecFitterDict()
{
  G__Sizep2memfuncXsecFitterDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceXsecFitterDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__XsecFitterDictLN_XsecFitter))) {
     XsecFitter *G__Lderived;
     G__Lderived=(XsecFitter*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__XsecFitterDictLN_XsecFitter),G__get_linked_tagnum(&G__XsecFitterDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableXsecFitterDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<AnaEvent>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEAnaEventcOallocatorlEAnaEventgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEAnaEventcOallocatorlEAnaEventgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEAnaEventcOallocatorlEAnaEventgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEAnaEventcOallocatorlEAnaEventgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEAnaEventcOallocatorlEAnaEventgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__XsecFitterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<double,double> >",117,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEpairlEdoublecOdoublegRcOallocatorlEpairlEdoublecOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<double,double> >",117,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEpairlEdoublecOdoublegRcOallocatorlEpairlEdoublecOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEpairlEdoublecOdoublegRcOallocatorlEpairlEdoublecOdoublegRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEpairlEdoublecOdoublegRcOallocatorlEpairlEdoublecOdoublegRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEpairlEdoublecOdoublegRcOallocatorlEpairlEdoublecOdoublegRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEpairlEdoublecOdoublegRcOallocatorlEpairlEdoublecOdoublegRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<double,double> >",117,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEpairlEdoublecOdoublegRcOallocatorlEpairlEdoublecOdoublegRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSym<Double_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TMatrixTSymlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Double_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TMatrixTRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Double_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TMatrixTColumn_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Double_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TMatrixTDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Double_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TMatrixTFlat_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Double_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TMatrixTSub_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Double_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TMatrixTSparseRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Double_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TMatrixTSparseDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Double_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TMatrixTRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Double_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TMatrixTColumnlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Double_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TMatrixTDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Double_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TMatrixTFlatlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Double_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TMatrixTSublEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Double_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TMatrixTSparseRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Double_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TMatrixTSparseDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Double_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TElementActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Double_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TElementPosActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparse<Double_t>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_TMatrixTSparselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<AnaSample*>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEAnaSamplemUcOallocatorlEAnaSamplemUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEAnaSamplemUcOallocatorlEAnaSamplemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEAnaSamplemUcOallocatorlEAnaSamplemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEAnaSamplemUcOallocatorlEAnaSamplemUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEAnaSamplemUcOallocatorlEAnaSamplemUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::string>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::vector<int> >",117,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<int> >",117,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<int,allocator<int> > >",117,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<AnaFitParameters*>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEAnaFitParametersmUcOallocatorlEAnaFitParametersmUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEAnaFitParametersmUcOallocatorlEAnaFitParametersmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEAnaFitParametersmUcOallocatorlEAnaFitParametersmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEAnaFitParametersmUcOallocatorlEAnaFitParametersmUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEAnaFitParametersmUcOallocatorlEAnaFitParametersmUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::vector<double> >",117,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double> >",117,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<vector<double,allocator<double> > >",117,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* XsecFitter */
static void G__setup_memvarXsecFitter(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__XsecFitterDictLN_XsecFitter));
   { XsecFitter *p; p=(XsecFitter*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__XsecFitterDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__XsecFitterDictLN_TH1D),-1,-1,4,"mcHisto=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__XsecFitterDictLN_TRandom3),-1,-1,4,"rand=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__XsecFitterDictLN_TDirectory),-1,-1,4,"m_dir=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEAnaFitParametersmUcOallocatorlEAnaFitParametersmUgRsPgR),G__defined_typename("vector<AnaFitParameters*>"),-1,4,"m_fitpara=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEintcOallocatorlEintgRsPgR),G__defined_typename("vector<int>"),-1,4,"m_nparclass=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEAnaSamplemUcOallocatorlEAnaSamplemUgRsPgR),G__defined_typename("vector<AnaSample*>"),-1,4,"m_samples=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"m_npar=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"m_calls=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"m_freq=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,4,"reg_p1=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEstringcOallocatorlEstringgRsPgR),G__defined_typename("vector<std::string>"),-1,4,"par_names=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"par_prefit=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"par_postfit=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"par_errfit=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"par_toydata=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"vec_chi2_stat=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__XsecFitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR),G__defined_typename("vector<double>"),-1,4,"vec_chi2_sys=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarXsecFitterDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncXsecFitter(void) {
   /* XsecFitter */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__XsecFitterDictLN_XsecFitter));
   G__memfunc_setup("XsecFitter",1025,G__XsecFitterDict_630_0_1, 105, G__get_linked_tagnum(&G__XsecFitterDictLN_XsecFitter), -1, 0, 1, 1, 1, 0, "i - - 0 '1019' seed", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSeed",685,G__XsecFitterDict_630_0_2, 121, -1, -1, 0, 1, 1, 1, 0, "i - - 0 - seed", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("fcn",311,G__XsecFitterDict_630_0_3, 121, -1, -1, 0, 5, 1, 1, 0, 
"i - 'Int_t' 1 - npar D - 'Double_t' 0 - gin "
"d - 'Double_t' 1 - f D - 'Double_t' 0 - par "
"i - 'Int_t' 0 - iflag", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("InitFitter",1026,G__XsecFitterDict_630_0_4, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'vector<AnaFitParameters*,allocator<AnaFitParameters*> >' 'vector<AnaFitParameters*>' 1 - fitpara d - 'Double_t' 0 - reg", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FixParameter",1224,G__XsecFitterDict_630_0_5, 121, -1, -1, 0, 2, 1, 1, 0, 
"u 'string' - 0 - par_name d - - 0 - value", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Fit",291,G__XsecFitterDict_630_0_6, 121, -1, -1, 0, 3, 1, 1, 0, 
"u 'vector<AnaSample*,allocator<AnaSample*> >' 'vector<AnaSample*>' 1 - samples i - - 0 - datatype "
"i - - 0 - fitMethod", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetSaveMode",1088,G__XsecFitterDict_630_0_7, 121, -1, -1, 0, 2, 1, 1, 0, 
"U 'TDirectory' - 0 - dirout i - - 0 - freq", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__XsecFitterDict_630_0_8, 85, G__get_linked_tagnum(&G__XsecFitterDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&XsecFitter::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__XsecFitterDict_630_0_9, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&XsecFitter::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__XsecFitterDict_630_0_10, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&XsecFitter::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__XsecFitterDict_630_0_11, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&XsecFitter::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__XsecFitterDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__XsecFitterDict_630_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__XsecFitterDict_630_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&XsecFitter::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__XsecFitterDict_630_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&XsecFitter::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__XsecFitterDict_630_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&XsecFitter::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__XsecFitterDict_630_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&XsecFitter::DeclFileLine) ), 0);
   G__memfunc_setup("GenerateToyData",1505,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 2, 1, 4, 0, 
"i - - 0 '0' toyindx i - - 0 '0' toytype", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("FillSamples",1116,(G__InterfaceMethod) NULL, 100, -1, -1, 0, 2, 1, 4, 0, 
"u 'vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >' 'vector<std::vector<double> >' 0 - new_pars i - - 0 '0' datatype", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSaveParams",1190,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "u 'vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >' 'vector<std::vector<double> >' 0 - new_pars", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSaveEvents",1207,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 1, 1, 4, 0, "i - - 0 - fititer", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSaveChi2",904,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("CollectSampleHistos",1954,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoSaveResults",1332,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 7, 1, 4, 0, 
"u 'vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >' 'vector<std::vector<double> >' 0 - parresults u 'vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >' 'vector<std::vector<double> >' 0 - parerrors "
"u 'vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >' 'vector<std::vector<double> >' 0 - parerrorsplus u 'vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >' 'vector<std::vector<double> >' 0 - parerrorsminus "
"u 'vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >' 'vector<std::vector<double> >' 0 - parerrorspara u 'vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >' 'vector<std::vector<double> >' 0 - parerrorsglobc "
"d - - 0 - chi2", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("XsecFitter", 1025, G__XsecFitterDict_630_0_27, (int) ('i'), G__get_linked_tagnum(&G__XsecFitterDictLN_XsecFitter), -1, 0, 1, 1, 1, 0, "u 'XsecFitter' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~XsecFitter", 1151, G__XsecFitterDict_630_0_28, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__XsecFitterDict_630_0_29, (int) ('u'), G__get_linked_tagnum(&G__XsecFitterDictLN_XsecFitter), -1, 1, 1, 1, 1, 0, "u 'XsecFitter' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncXsecFitterDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalXsecFitterDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcXsecFitterDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__XsecFitterDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TDirectory = { "TDirectory" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR = { "vector<double,allocator<double> >" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TRandom3 = { "TRandom3" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TH1D = { "TH1D" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__XsecFitterDictLN_vectorlEAnaEventcOallocatorlEAnaEventgRsPgR = { "vector<AnaEvent,allocator<AnaEvent> >" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_reverse_iteratorlEvectorlEAnaEventcOallocatorlEAnaEventgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<AnaEvent,allocator<AnaEvent> >::iterator>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_vectorlEpairlEdoublecOdoublegRcOallocatorlEpairlEdoublecOdoublegRsPgRsPgR = { "vector<pair<double,double>,allocator<pair<double,double> > >" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_reverse_iteratorlEvectorlEpairlEdoublecOdoublegRcOallocatorlEpairlEdoublecOdoublegRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<double,double>,allocator<pair<double,double> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TElementActionTlEdoublegR = { "TElementActionT<double>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TElementPosActionTlEdoublegR = { "TElementPosActionT<double>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TMatrixTSymlEdoublegR = { "TMatrixTSym<double>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TMatrixTRow_constlEdoublegR = { "TMatrixTRow_const<double>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TMatrixTRowlEdoublegR = { "TMatrixTRow<double>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TMatrixTColumn_constlEdoublegR = { "TMatrixTColumn_const<double>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TMatrixTDiag_constlEdoublegR = { "TMatrixTDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TMatrixTFlat_constlEdoublegR = { "TMatrixTFlat_const<double>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TMatrixTSub_constlEdoublegR = { "TMatrixTSub_const<double>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TMatrixTSparseRow_constlEdoublegR = { "TMatrixTSparseRow_const<double>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TMatrixTSparselEdoublegR = { "TMatrixTSparse<double>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TMatrixTSparseDiag_constlEdoublegR = { "TMatrixTSparseDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TMatrixTColumnlEdoublegR = { "TMatrixTColumn<double>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TMatrixTDiaglEdoublegR = { "TMatrixTDiag<double>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TMatrixTFlatlEdoublegR = { "TMatrixTFlat<double>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TMatrixTSublEdoublegR = { "TMatrixTSub<double>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TMatrixTSparseRowlEdoublegR = { "TMatrixTSparseRow<double>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_TMatrixTSparseDiaglEdoublegR = { "TMatrixTSparseDiag<double>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_vectorlEAnaSamplemUcOallocatorlEAnaSamplemUgRsPgR = { "vector<AnaSample*,allocator<AnaSample*> >" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_reverse_iteratorlEvectorlEAnaSamplemUcOallocatorlEAnaSamplemUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<AnaSample*,allocator<AnaSample*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR = { "vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<int,allocator<int> >,allocator<vector<int,allocator<int> > > >::iterator>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_XsecFitter = { "XsecFitter" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_vectorlEAnaFitParametersmUcOallocatorlEAnaFitParametersmUgRsPgR = { "vector<AnaFitParameters*,allocator<AnaFitParameters*> >" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_reverse_iteratorlEvectorlEAnaFitParametersmUcOallocatorlEAnaFitParametersmUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<AnaFitParameters*,allocator<AnaFitParameters*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR = { "vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >" , 99 , -1 };
G__linked_taginfo G__XsecFitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<vector<double,allocator<double> >,allocator<vector<double,allocator<double> > > >::iterator>" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableXsecFitterDict() {
  G__XsecFitterDictLN_TClass.tagnum = -1 ;
  G__XsecFitterDictLN_TBuffer.tagnum = -1 ;
  G__XsecFitterDictLN_TDirectory.tagnum = -1 ;
  G__XsecFitterDictLN_TMemberInspector.tagnum = -1 ;
  G__XsecFitterDictLN_TObject.tagnum = -1 ;
  G__XsecFitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR.tagnum = -1 ;
  G__XsecFitterDictLN_string.tagnum = -1 ;
  G__XsecFitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__XsecFitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__XsecFitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__XsecFitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__XsecFitterDictLN_TRandom3.tagnum = -1 ;
  G__XsecFitterDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__XsecFitterDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__XsecFitterDictLN_TH1D.tagnum = -1 ;
  G__XsecFitterDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__XsecFitterDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__XsecFitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__XsecFitterDictLN_vectorlEAnaEventcOallocatorlEAnaEventgRsPgR.tagnum = -1 ;
  G__XsecFitterDictLN_reverse_iteratorlEvectorlEAnaEventcOallocatorlEAnaEventgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__XsecFitterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__XsecFitterDictLN_vectorlEpairlEdoublecOdoublegRcOallocatorlEpairlEdoublecOdoublegRsPgRsPgR.tagnum = -1 ;
  G__XsecFitterDictLN_reverse_iteratorlEvectorlEpairlEdoublecOdoublegRcOallocatorlEpairlEdoublecOdoublegRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__XsecFitterDictLN_TElementActionTlEdoublegR.tagnum = -1 ;
  G__XsecFitterDictLN_TElementPosActionTlEdoublegR.tagnum = -1 ;
  G__XsecFitterDictLN_TMatrixTSymlEdoublegR.tagnum = -1 ;
  G__XsecFitterDictLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G__XsecFitterDictLN_TMatrixTRow_constlEdoublegR.tagnum = -1 ;
  G__XsecFitterDictLN_TMatrixTRowlEdoublegR.tagnum = -1 ;
  G__XsecFitterDictLN_TMatrixTColumn_constlEdoublegR.tagnum = -1 ;
  G__XsecFitterDictLN_TMatrixTDiag_constlEdoublegR.tagnum = -1 ;
  G__XsecFitterDictLN_TMatrixTFlat_constlEdoublegR.tagnum = -1 ;
  G__XsecFitterDictLN_TMatrixTSub_constlEdoublegR.tagnum = -1 ;
  G__XsecFitterDictLN_TMatrixTSparseRow_constlEdoublegR.tagnum = -1 ;
  G__XsecFitterDictLN_TMatrixTSparselEdoublegR.tagnum = -1 ;
  G__XsecFitterDictLN_TMatrixTSparseDiag_constlEdoublegR.tagnum = -1 ;
  G__XsecFitterDictLN_TMatrixTColumnlEdoublegR.tagnum = -1 ;
  G__XsecFitterDictLN_TMatrixTDiaglEdoublegR.tagnum = -1 ;
  G__XsecFitterDictLN_TMatrixTFlatlEdoublegR.tagnum = -1 ;
  G__XsecFitterDictLN_TMatrixTSublEdoublegR.tagnum = -1 ;
  G__XsecFitterDictLN_TMatrixTSparseRowlEdoublegR.tagnum = -1 ;
  G__XsecFitterDictLN_TMatrixTSparseDiaglEdoublegR.tagnum = -1 ;
  G__XsecFitterDictLN_vectorlEAnaSamplemUcOallocatorlEAnaSamplemUgRsPgR.tagnum = -1 ;
  G__XsecFitterDictLN_reverse_iteratorlEvectorlEAnaSamplemUcOallocatorlEAnaSamplemUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__XsecFitterDictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__XsecFitterDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__XsecFitterDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__XsecFitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__XsecFitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR.tagnum = -1 ;
  G__XsecFitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__XsecFitterDictLN_XsecFitter.tagnum = -1 ;
  G__XsecFitterDictLN_vectorlEAnaFitParametersmUcOallocatorlEAnaFitParametersmUgRsPgR.tagnum = -1 ;
  G__XsecFitterDictLN_reverse_iteratorlEvectorlEAnaFitParametersmUcOallocatorlEAnaFitParametersmUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__XsecFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR.tagnum = -1 ;
  G__XsecFitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableXsecFitterDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TDirectory);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_string);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TRandom3);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TH1D);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_vectorlEAnaEventcOallocatorlEAnaEventgRsPgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEAnaEventcOallocatorlEAnaEventgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_vectorlEpairlEdoublecOdoublegRcOallocatorlEpairlEdoublecOdoublegRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEpairlEdoublecOdoublegRcOallocatorlEpairlEdoublecOdoublegRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TElementActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TElementPosActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TMatrixTSymlEdoublegR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TMatrixTRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TMatrixTRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TMatrixTColumn_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TMatrixTDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TMatrixTFlat_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TMatrixTSub_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TMatrixTSparseRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TMatrixTSparselEdoublegR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TMatrixTSparseDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TMatrixTColumnlEdoublegR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TMatrixTDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TMatrixTFlatlEdoublegR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TMatrixTSublEdoublegR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TMatrixTSparseRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_TMatrixTSparseDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_vectorlEAnaSamplemUcOallocatorlEAnaSamplemUgRsPgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEAnaSamplemUcOallocatorlEAnaSamplemUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_vectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRcOallocatorlEvectorlEintcOallocatorlEintgRsPgRsPgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_XsecFitter),sizeof(XsecFitter),-1,29952,(char*)NULL,G__setup_memvarXsecFitter,G__setup_memfuncXsecFitter);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_vectorlEAnaFitParametersmUcOallocatorlEAnaFitParametersmUgRsPgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEAnaFitParametersmUcOallocatorlEAnaFitParametersmUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__XsecFitterDictLN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRsPgRsPgRcLcLiteratorgR);
}
extern "C" void G__cpp_setupXsecFitterDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupXsecFitterDict()");
  G__set_cpp_environmentXsecFitterDict();
  G__cpp_setup_tagtableXsecFitterDict();

  G__cpp_setup_inheritanceXsecFitterDict();

  G__cpp_setup_typetableXsecFitterDict();

  G__cpp_setup_memvarXsecFitterDict();

  G__cpp_setup_memfuncXsecFitterDict();
  G__cpp_setup_globalXsecFitterDict();
  G__cpp_setup_funcXsecFitterDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncXsecFitterDict();
  return;
}
class G__cpp_setup_initXsecFitterDict {
  public:
    G__cpp_setup_initXsecFitterDict() { G__add_setup_func("XsecFitterDict",(G__incsetup)(&G__cpp_setupXsecFitterDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initXsecFitterDict() { G__remove_setup_func("XsecFitterDict"); }
};
G__cpp_setup_initXsecFitterDict G__cpp_setup_initializerXsecFitterDict;

