#!/bin/bash
# Wrap a ROOT macro as a script.
#
#  Check the output of GUNDAM 200NormalizationFit.sh against the
#  expected values.
#
root -b -n <<EOF
#include <iostream>
#include <string>
#include <memory>
#include <cmath>

#include <TFile.h>
#include <TH1.h>

std::string args{"$*"};
int status{0};

/// Fail with message if "v1" evaluates to false.  THIS IS COPIED
/// HERE TO AVOID DEPENDENCIES
#define EXPECT(msg,v1)                                      \
    do {                                                    \
        if (not (v1)) {                                     \
            std::cout << "FAIL:";                           \
            ++ status;                                      \
        } else {                                            \
            std::cout << "SUCCESS:";                        \
        }                                                   \
        std::cout << " " << msg                             \
                  << " [ (" << #v1 << ") --> " << v1 << "]" \
                  << std::endl;                             \
    } while (false)

/// Fail if fractional difference between "v1" and "v2" is larger than "tol"
/// THIS IS COPIED HERE TO AVOID DEPENDENCIES
#define TOLERANCE(msg,v1,v2,tol)                            \
    do {                                                    \
        double v = (v1)>0 ? (v1): -(v1);                    \
        double vv = (v2)>0 ? (v2): -(v2);                   \
        double d = std::abs((v1)-(v2));                     \
        double r = d/std::max(0.5*(v+vv),(tol));            \
        if (r > (tol)) {                                    \
            std::cout << "FAIL:";                           \
            ++ status;                                      \
        } else {                                            \
            std::cout << "SUCCESS:";                        \
        }                                                   \
        std::cout << " " << msg                             \
                  << std::setprecision(8)                   \
                  << std::scientific                        \
                  << " (" << r << "<" << (tol) << ")"       \
                  << " [" << #v1 << "=" << (v1)             \
                  << " " << #v2 << "=" << (v2)              \
                  << " " << d << "]"                        \
                  << std::endl;                             \
    } while(false);

int main() {
    std::shared_ptr<TFile> file(new TFile("200NormalizationFit.root","old"));

    EXPECT("File pointer is not null",file);
    if (!file) return status;

    EXPECT("File must be open", file->IsOpen());
    if (not file->IsOpen()) return status;

    TH1* postFitErrorsMigrad
        = dynamic_cast<TH1*>(file->Get(
                                 "FitterEngine"
                                 "/postFit"
                                 "/Migrad"
                                 "/errors"
                                 "/Normalizations"
                                 "/values"
                                 "/postFitErrors_TH1D"));
    EXPECT("postFitErrors must exist",  postFitErrorsMigrad);

    TH1* postFitErrorsHesse
        = dynamic_cast<TH1*>(file->Get(
                                 "FitterEngine"
                                 "/postFit"
                                 "/Hesse"
                                 "/errors"
                                 "/Normalizations"
                                 "/values"
                                 "/postFitErrors_TH1D"));
    EXPECT("postFitErrors must exist",  postFitErrorsHesse);

    TMatrixD* covariance
        = dynamic_cast<TMatrixD*>(file->Get(
                                      "FitterEngine"
                                      "/postFit"
                                      "/Hesse"
                                      "/errors"
                                      "/Normalizations"
                                      "/matrices"
                                      "/Covariance_TMatrixD"));
    EXPECT("covariance must exist",  covariance);

    // Don't try to continue if the data is missing from the file.
    if (not postFitErrorsMigrad) return status;
    if (not postFitErrorsHesse) return status;
    if (not covariance) return status;

    postFitErrorsMigrad->Draw();
    gPad->Print("900NormalizationFitCheck.pdf[");
    postFitErrorsHesse->Draw();
    gPad->Print("900NormalizationFitCheck.pdf");
    gPad->Print("900NormalizationFitCheck.pdf]");

    covariance->Print();

    // Change this to set the expected absolute tolerance.
    double tolerance = 1E-6;

    // The expected values are for the data generated by
    // 100NormalizationTree.C.  They need to be changed if that tree is
    // changed.
    TOLERANCE("Check HESSE value for #0_Positive_C",
              postFitErrorsHesse->GetBinContent(1), 7.96683932e-01, tolerance);
    TOLERANCE("Check MIGRAD matches HESSE value for #0_Positive_C",
              postFitErrorsMigrad->GetBinContent(1),
              postFitErrorsHesse->GetBinContent(1), 1E-12);
    TOLERANCE("Check variance for #0_Positive_C",
              (*covariance)(0,0), 1.10574664e-04, tolerance);

    TOLERANCE("Check HESSE value for #1_Negative_C",
              postFitErrorsHesse->GetBinContent(2), 5.88292045e-01, tolerance);
    TOLERANCE("Check MIGRAD matches HESSE value for #1_Negative_C",
              postFitErrorsMigrad->GetBinContent(2),
               postFitErrorsHesse->GetBinContent(2), 1E-12);
    TOLERANCE("Check variance for #1_Negative_C",
              (*covariance)(1,1), 8.97100595e-05, tolerance);

    TOLERANCE("Check covariance",
              (*covariance)(0,1), -3.08874630e-05, tolerance);

    file->Close();

    return status;
}
exit(main());
EOF
# Local Variables:
# mode:c++
# c-basic-offset:4
# End:
